module.exports = {
  modulesSidebar: [
      {
          type: 'autogenerated',
          dirName: '.'
      }
    //   'introduction',
    //   {
    //       'Piston Cylinder': [
    //           'piston-cylinder/introduction',
    //           {
    //               'Background': [
    //                   'piston-cylinder/first-law',
    //                   'piston-cylinder/reversible-processes',
    //                   'piston-cylinder/model',
    //               ]
    //           }
    //       ],
    //   }
  ],
};