mods = require('./src/modules.json')

const sidebar = Object.fromEntries(
  mods.map((mod, idx) => {
    const order = `${idx+1}`.padStart(2, '0');
    return [
      `${mod.title}`.replace(' ','_'),
      [
        {
          [`${mod.title}`]: [
            {
              type: 'autogenerated',
              dirName: `${order}-${mod.title}`
            }
          ]
        }
      ]
    ]
  })
)

module.exports = sidebar

// module.exports = {
//   modulesSidebar: [

//       // {
//       //     type: 'autogenerated',
//       //     dirName: '.'
//       // }
//     //   'introduction',
//     //   {
//     //       'Piston Cylinder': [
//     //           'piston-cylinder/introduction',
//     //           {
//     //               'Background': [
//     //                   'piston-cylinder/first-law',
//     //                   'piston-cylinder/reversible-processes',
//     //                   'piston-cylinder/model',
//     //               ]
//     //           }
//     //       ],
//     //   }
//   ],

//   PistonCylinder: [
//     {
//       'Piston-Cylinder': [
//         {
//           type: 'autogenerated',
//           dirName: '01-Piston-Cylinder'

//         }
//       ]
//     }
//   ]
// };